language: node_js
node_js: node
cache:
  yarn: true

install: yarn install

jobs:
  include:
    - stage: build
      script: yarn build

deploy:
  local-dir: build
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
