language: node_js
node_js: lts/*
cache:
  yarn: true

install: yarn install --production=false

jobs:
  include:
    - stage: build
      script: yarn build

deploy:
  local-dir: build
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
