language: node_js
node_js: lts/*
cache:
  yarn: true
  timeout: 1000

install: yarn install --production=false

jobs:
  include:
    - stage: build
      script: yarn build
      on:
        branch: master

deploy:
  local-dir: build
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
